# Generated by Django 5.2.1 on 2025-06-09 14:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_managers_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Даты и время создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='creator',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.PROTECT, related_name='created_teams', to='account.worker', verbose_name='Создатель'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Даты и время обновления'),
        ),
    ]
