services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: ["python", "manage.py", "test"]
  db:
    image: postgres:17-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"