volumes:
  pg_data:
  static_file:

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - static_file:/app/staticfiles
    depends_on:
      - db
  db:
    image: postgres:17-alpine
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  nginx:
    image: nginx:alpine
    ports:
     - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_file:/app/staticfiles
    depends_on:
      - backend
    