# Generated by Django 5.2.1 on 2025-05-14 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_team_worker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='Дата и время встречи')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_meetings', to='account.worker', verbose_name='Инициатор встречи')),
            ],
        ),
        migrations.CreateModel(
            name='MeetingWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.meeting')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.worker')),
            ],
        ),
        migrations.AddField(
            model_name='meeting',
            name='workers',
            field=models.ManyToManyField(related_name='meetings', through='event.MeetingWorker', to='account.worker', verbose_name='Сотрудники приглашенные на встречу'),
        ),
    ]
