# Generated by Django 5.2.1 on 2025-05-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='description',
            field=models.TextField(default='', verbose_name='Детали встречи'),
        ),
    ]
