# Generated by Django 5.2.1 on 2025-05-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_meeting_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='description',
            field=models.TextField(verbose_name='Детали встречи'),
        ),
    ]
