# Generated by Django 5.2.1 on 2025-05-14 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_team_worker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование задачи')),
                ('description', models.TextField(verbose_name='Описание задачи')),
                ('deadline', models.DateTimeField(verbose_name='Крайний срок')),
                ('status', models.CharField(choices=[('OP', 'Открыто'), ('AW', 'В работе'), ('DN', 'Выполнено')], default='OP', max_length=2, verbose_name='Статус задачи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Даты и время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Даты и время обновления')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tasks', to='account.worker', verbose_name='Создатель')),
                ('executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed_tasks', to='account.worker', verbose_name='Исполнитель')),
            ],
        ),
    ]
