# Generated by Django 5.2.1 on 2025-05-14 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_team_worker'),
        ('task', '0002_evaluation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Даты и время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Даты и время обновления')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='comments', to='account.worker', verbose_name='Автор комментария')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='task.task', verbose_name='Комментируемая задача')),
            ],
        ),
    ]
