# Generated by Django 5.2.1 on 2025-06-11 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_team_creator'),
        ('task', '0005_alter_task_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='account.worker', verbose_name='Автор комментария'),
        ),
    ]
